export const defaultTheme = {
  Key: 0,
  PrimaryColor: "#FFEB3B",
  DarkPrimaryColor: "#FBC02D",
  LightPrimaryColor: "#FFF9C4",
  PrimaryTextColor: "#c19017",
  SecondaryColor: "#CDDC39",
  DarkSecondaryColor: "#AFB42B",
  LightSecondaryColor: "#F0F4C3",
  SecondaryTextColor: "#757575",
};

export const availableThemes = [
  defaultTheme,
  {
    Key: 1,
    PrimaryColor: "#CDDC39",
    DarkPrimaryColor: "#AFB42B",
    LightPrimaryColor: "#212121",
    PrimaryTextColor: "#7a7e07",
    SecondaryColor: "#CDDC39",
    DarkSecondaryColor: "#AFB42B",
    LightSecondaryColor: "#F0F4C3",
    SecondaryTextColor: "#7a7e07",
  },
  {
    Key: 2,
    PrimaryColor: "#fda7c4",
    DarkPrimaryColor: "#ff4081",
    LightPrimaryColor: "#ffdae6",
    PrimaryTextColor: "#ff679b",
    SecondaryColor: "#fda7c4",
    DarkSecondaryColor: "#ff4081",
    LightSecondaryColor: "#ffdae6",
    SecondaryTextColor: "#ff679b",
  },
  {
    Key: 3,
    PrimaryColor: "#6bd1ff",
    DarkPrimaryColor: "#448AFF",
    LightPrimaryColor: "#B3E5FC",
    PrimaryTextColor: "#0288D1",
    SecondaryColor: "#6bd1ff",
    DarkSecondaryColor: "#448AFF",
    LightSecondaryColor: "#B3E5FC",
    SecondaryTextColor: "#0288D1",
  },
];
